-- Quiz lead capture infrastructure for Stellr marketing site

BEGIN;

CREATE TABLE IF NOT EXISTS public.quiz_leads (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email text UNIQUE NOT NULL,
    birth_date date NOT NULL,
    birth_time time,
    birth_location text NOT NULL,
    birth_lat numeric,
    birth_lng numeric,
    timezone text,
    question_1_answer text,
    question_2_answer text,
    question_3_answer text,
    quiz_results jsonb,
    source text DEFAULT 'website_quiz',
    session_id text,
    ip_address inet,
    user_agent text,
    subscribed_at timestamptz DEFAULT now(),
    converted_to_app boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT quiz_leads_valid_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')
);

CREATE INDEX IF NOT EXISTS idx_quiz_leads_email ON public.quiz_leads(email);
CREATE INDEX IF NOT EXISTS idx_quiz_leads_subscribed_at ON public.quiz_leads(subscribed_at DESC);
CREATE INDEX IF NOT EXISTS idx_quiz_leads_session_id ON public.quiz_leads(session_id);
CREATE INDEX IF NOT EXISTS idx_quiz_leads_ip_time ON public.quiz_leads(ip_address, subscribed_at DESC);

ALTER TABLE public.quiz_leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role manage quiz leads" ON public.quiz_leads;
CREATE POLICY "Service role manage quiz leads"
    ON public.quiz_leads
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

CREATE TABLE IF NOT EXISTS public.quiz_lead_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL,
    event_type text NOT NULL,
    step int,
    properties jsonb,
    email text,
    ip_address inet,
    occurred_at timestamptz DEFAULT now(),
    CONSTRAINT quiz_lead_events_step CHECK (step IS NULL OR step BETWEEN 1 AND 7)
);

CREATE INDEX IF NOT EXISTS idx_quiz_lead_events_session ON public.quiz_lead_events(session_id);
CREATE INDEX IF NOT EXISTS idx_quiz_lead_events_type ON public.quiz_lead_events(event_type);
CREATE INDEX IF NOT EXISTS idx_quiz_lead_events_occured ON public.quiz_lead_events(occurred_at DESC);

ALTER TABLE public.quiz_lead_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manage quiz events" ON public.quiz_lead_events;
CREATE POLICY "Service role manage quiz events"
    ON public.quiz_lead_events
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

CREATE TABLE IF NOT EXISTS public.quiz_nurture_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_lead_id uuid REFERENCES public.quiz_leads(id) ON DELETE CASCADE,
    sequence_step text NOT NULL,
    scheduled_for timestamptz NOT NULL,
    status text DEFAULT 'pending',
    metadata jsonb,
    created_at timestamptz DEFAULT now(),
    processed_at timestamptz,
    CONSTRAINT quiz_nurture_queue_valid_step CHECK (sequence_step IN ('day0', 'day1', 'day3', 'day7')),
    CONSTRAINT quiz_nurture_queue_valid_status CHECK (status IN ('pending', 'processing', 'sent', 'error'))
);

CREATE INDEX IF NOT EXISTS idx_quiz_nurture_queue_scheduled ON public.quiz_nurture_queue(status, scheduled_for);
CREATE INDEX IF NOT EXISTS idx_quiz_nurture_queue_lead ON public.quiz_nurture_queue(quiz_lead_id);

ALTER TABLE public.quiz_nurture_queue ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manage nurture queue" ON public.quiz_nurture_queue;
CREATE POLICY "Service role manage nurture queue"
    ON public.quiz_nurture_queue
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

CREATE TABLE IF NOT EXISTS public.resend_event_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    email text,
    message_id text,
    payload jsonb,
    received_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_resend_event_log_email ON public.resend_event_log(email);
CREATE INDEX IF NOT EXISTS idx_resend_event_log_received ON public.resend_event_log(received_at DESC);

ALTER TABLE public.resend_event_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manage resend events" ON public.resend_event_log;
CREATE POLICY "Service role manage resend events"
    ON public.resend_event_log
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

CREATE TABLE IF NOT EXISTS public.transactional_email_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    email text NOT NULL,
    event_type text NOT NULL,
    template_version text,
    payload jsonb,
    status text DEFAULT 'pending',
    error_message text,
    created_at timestamptz DEFAULT now(),
    processed_at timestamptz,
    CONSTRAINT transactional_email_queue_status CHECK (status IN ('pending','processing','sent','error'))
);

CREATE INDEX IF NOT EXISTS idx_transactional_email_queue_status ON public.transactional_email_queue(status, created_at);
CREATE INDEX IF NOT EXISTS idx_transactional_email_queue_user ON public.transactional_email_queue(user_id);

ALTER TABLE public.transactional_email_queue ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manage transactional queue" ON public.transactional_email_queue;
CREATE POLICY "Service role manage transactional queue"
    ON public.transactional_email_queue
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

CREATE TABLE IF NOT EXISTS public.resend_template_registry (
    template_id text PRIMARY KEY,
    description text,
    version text NOT NULL,
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.resend_template_registry ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Service role manage template registry" ON public.resend_template_registry;
CREATE POLICY "Service role manage template registry"
    ON public.resend_template_registry
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

COMMIT;
